# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# forge
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2.0)
forge_version=26.1.2.41-beta
forge_version_range=[26.1.2.41-beta,)

# mod
mod_id=guideapi_vp
mod_name=Guide-API-VP
mod_license=MIT
main_version=3
major_version=0
minor_version=0
mod_group_id=de.maxanier.guideapi
mod_authors=maxanier, TehNut, Tombenpotter
mod_description=Library mod for easy creation of guide books in Java.
mod_url=https://github.com/maxanier/Guide-API
mod_issue_tracker=https://github.com/maxanier/Guide-API/issues
modrinth_id=w5L2PHJU7
curseforge_id=380771
curseforge_slug=guide-api-village-and-pillage

# properties will be overridden in gradle/versioning.gradle
mod_version="Test"
type="test"
classification="test"

#jei setting
include_jei=true
jei_mc_version=26.1.2
jei_version=29.5.0.28


