# gradle
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.debug=false

# forge
minecraft_version=1.21.0
minecraft_version_range=[1.21,1.22)
forge_version=21.0.42-beta
forge_version_range=[21.0.42-beta,)
loader_version_range=[1,)
parchment_minecraft_version=1.20.6
parchment_mappings_version=2024.06.02
pack_format_number=18

# mod
mod_id=guideapi_vp
mod_name=Guide-API-VP
mod_license=MIT
main_version=2
major_version=3
minor_version=0
mod_group_id=de.maxanier.guideapi
mod_authors=maxanier, TehNut, Tombenpotter
mod_description=Library mod for easy creation of guide books in Java.
mod_url=https://github.com/maxanier/Guide-API
mod_issue_tracker=https://github.com/maxanier/Guide-API/issues
modrinth_id=w5L2PHJU
curseforge_id=380771
curseforge_slug=guide-api-village-and-pillage

# properties will be overridden in gradle/versioning.gradle
mod_version="Test"
type="test"
classification="test"

#jei setting
include_jei=false
jei_mc_version=1.20.4
jei_version=17.3.0.48


