apply plugin: 'maven-publish'
tasks.withType(GenerateModuleMetadata) {
    enabled = false
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.mod_name
            version project.version
            from components.java


            pom {
                description = 'A programmatic GuideBook API for MC'

                scm {
                    url = 'https://github.com/maxanier/Guide-API'
                    connection = 'scm:git:git://github.com/maxanier/Guide-API.git'
                    developerConnection = 'scm:git:git@github.com:maxanier/Guide-API.git'
                }

                issueManagement {
                    system = 'github'
                    url = 'https://github.com/maxanier/Guide-API/issues'
                }

                developers {
                    developer {
                        id = 'maxanier'
                        name = 'maxanier'
                        roles = ["developer"]
                    }
                }
            }

            artifact sourcesJar
            artifact javadocJar

        }
    }

    repositories {
        maven {
            // Sets the login credentials for your maven.
            credentials {
                username findProperty('maxanier_maven_alias')
                password findProperty('maxanier_maven_token')
            }

            // Sets the maven URL
            url findProperty('maxanier_maven_url')
        }
    }
}

tasks.register('checkIfPublicVersion') {
    doFirst {
        if (project.classification != "public") {
            throw new PublishException("Trying to publish a version that is not intended for public release")
        }
    }
}

tasks.register('publishAll') {
    dependsOn('build')
    dependsOn('checkIfPublicVersion')
    dependsOn('publish')
    dependsOn('publishMods')
}

tasks.publishMods.dependsOn(checkIfPublicVersion)

publishMods {
    type = project.type == "beta" ? BETA: project.type == "release" ? STABLE : ALPHA
    changelog = !(findProperty("CHANGELOG") ?: "").toString().isEmpty() ? getProperty("CHANGELOG") : type != ALPHA ? "" : "This version should not be used in your 'productive' world. It contains the latest features, but also the latest bugs.\n Probably not all features are finished.\n To see what might have changed browse the latest commits."
    file = jar.archiveFile
    modLoaders.add("neoforge")
    version = "${project.minecraft_version}-${project.mod_version}"
    displayName = "Guide-API-VP-${project.minecraft_version}-${project.mod_version}"
    dryRun = !(project.hasProperty("MODRINTH_API") && project.hasProperty("CURSEFORGE_API"))

    modrinth {
        accessToken = findProperty("MODRINTH_API") ?: "DUMMY"
        projectId = project.modrinth_id
        minecraftVersions.add(project.minecraft_version)
    }

    curseforge {
        accessToken = findProperty("CURSEFORGE_API") ?: "DUMMY"
        projectId = project.curseforge_id
        minecraftVersions.add(project.minecraft_version)
        projectSlug = project.curseforge_slug
    }
}
